from typing import TypedDict, List, Dict, Any

class AuditorState(TypedDict):
    # The user's input legal query or question
    question: str

    # The category of legal document identified (e.g., Lease, NDA, Adoption, Trust, Property, Other)
    document_type: str

    # List of retrieved legal document chunks.
    # Each chunk is represented as a dictionary:
    # {"text": str, "source": str, "page": int, "score": float}
    legal_docs: List[Dict[str, Any]]

    # List of internal documents/policies (if applicable) for alignment checks
    internal_docs: List[str]

    # The result of the Evaluator Agent's inspection ("pass" or "fail")
    retrieval_grade: str

    # The final compliance audit report / legal memo generated by the Synthesizer
    audit_report: str

    # The search query sent to Qdrant (rewritten dynamically on retries)
    search_query: str

    # A counter tracking retrieval retries to prevent infinite loops
    retry_count: int